version: "3.7"
services:
  backend:
    build:
      context: .
      args:
        binary: backend
    ports:
    - 8080:80
    command: -port 80
  frontend:
    build:
      context: .
      args:
        binary: frontend
    ports:
      - 8081:80
    command:  -port 80 -backend-url http://backend:80
    environment:
      - JAEGER_SERVICE_NAME=frontend
      - JAEGER_ENDPOINT=http://jaeger:14268/api/traces
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
      - JAEGER_REPORTER_LOG_SPANS=true
  jaeger:
    image: jaegertracing/all-in-one:1.16.0
    ports:
    - 16686:16686
