version: "3.7"
services:
  backend:
    build:
      context: .
      args:
        binary: backend
        step:
    ports:
    - 8080:8080
    command: -port 8080
    environment:
      - JAEGER_SERVICE_NAME=backend
      - JAEGER_ENDPOINT=http://jaeger:14268/api/traces
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
      - JAEGER_REPORTER_LOG_SPANS=true
  frontend:
    build:
      context: .
      args:
        binary: frontend
        step:
    ports:
      - 8081:8081
    command:  -port 8081 -backend-url http://backend:8080
    environment:
      - JAEGER_SERVICE_NAME=frontend
      - JAEGER_ENDPOINT=http://jaeger:14268/api/traces
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
      - JAEGER_REPORTER_LOG_SPANS=true
  jaeger:
    image: jaegertracing/all-in-one:1.16.0
    ports:
    - 16686:16686
