version: "3.7"
services:
  backend:
    build:
      context: .
      args:
        binary: backend
    ports:
    - 8080:80
    command: -port 80
  frontend:
    build:
      context: .
      args:
        binary: frontend
    ports:
      - 8081:80
    command:  -port 80 -backend-url http://backend:80